// exports.animes =
//   [
//   "Naruto",
//   "One Piece",
//   "Bleach",
//   "Ninja Kamui",
//   "Attack on Titan",
//   "My Hero Academia",
//   "Death Note",
//   "Fullmetal Alchemist: Brotherhood",
//   "Dragon Ball Z",
//   "Sword Art Online",
//   "Demon Slayer",
//   "One Punch Man",
//   "Hunter x Hunter",
//   "Fairy Tail",
//   "Tokyo Ghoul",
//   "Cowboy Bebop",
//   "Neon Genesis Evangelion",
//   "Code Geass",
//   "Dragon Ball",
//   "JoJo's Bizarre Adventure",
//   "Steins;Gate",
//   "Mob Psycho 100",
//   "Black Clover",
//   "Kimetsu no Yaiba",
//   "Fate/stay night",
//   "Psycho-Pass",
//   "Fruits Basket",
//   "Re:Zero",
//   "Gurren Lagann",
//   "Yu Yu Hakusho",
//   "Noragami",
//   "Soul Eater",
//   "Durarara!!",
//   "Shingeki no Kyojin",
//   "Dragon Ball Super",
//   "The Seven Deadly Sins",
//   "Akame ga Kill!",
//   "Mirai Nikki",
//   "High School DxD",
//   "Gintama",
//   "Hellsing",
//   "Kuroko's Basketball",
//   "Death Parade",
//   "Violet Evergarden",
//   "No Game No Life",
//   "Clannad",
//   "Haikyuu!!",
//   "Angel Beats!",
//   "Tokyo Revengers",
//   "Kill la Kill",
//   "The Promised Neverland",
//   "Overlord",
//   "Parasyte",
//   "Elfen Lied",
//   "Toradora!",
//   "Attack on Titan: Junior High",
//   "Date A Live",
//   "Fairy Tail: Final Series",
//   "Goblin Slayer",
//   "Devilman: Crybaby",
//   "Nanatsu no Taizai",
//   "Hajime no Ippo",
//   "Baccano!",
//   "That Time I Got Reincarnated as a Slime",
//   "Akira",
//   "Sailor Moon",
//   "K-On!",
//   "Ao no Exorcist",
//   "Sword Art Online II",
//   "Shaman King",
//   "Boku dake ga Inai Machi",
//   "Charlotte",
//   "Made in Abyss",
//   "Black Butler",
//   "Devil May Cry",
//   "Love Live! School Idol Project",
//   "Kill Me Baby",
//   "Inuyasha",
//   "Konosuba",
//   "School Days",
//   "Shokugeki no Souma",
//   "Hyouka",
//   "Trigun",
//   "Rurouni Kenshin",
//   "Durarara!!x2 Shou",
//   "Yuri!!! on Ice",
//   "Mushishi",
//   "Danganronpa",
//   "The Rising of the Shield Hero",
//   "The Ancient Magus' Bride",
//   "Claymore",
//   "Another",
//   "Durarara!!x2 Ten",
//   "Tokyo Ghoul:re",
//   "Guilty Crown",
//   "Plastic Memories",
//   "Black Bullet",
//   "Devilman Lady",
//   "Magi: The Labyrinth of Magic",
//   "Mobile Suit Gundam",
//   "Trinity Seven",
//   "The Future Diary",
//   "To Love-Ru",
//   "Berserk",
//   "Your Lie in April",
//   "Initial D",
//   "Love, Chunibyo & Other Delusions!",
//   "Spice and Wolf",
//   "Puella Magi Madoka Magica",
//   "Rosario + Vampire",
//   "Darker than Black",
//   "Attack on Titan Season 3",
//   "Fruits Basket: The Final",
//   "Attack on Titan Season 2",
//   "Attack on Titan Season 4",
//   "Attack on Titan Season 1",
//   "The Seven Deadly Sins: Wrath of the Gods",
//   "Sword Art Online: Alicization",
//   "Sword Art Online: Alicization - War of Underworld",
//   "Sword Art Online: Alicization - War of Underworld 2nd Season",
//   "Attack on Titan: No Regrets",
//   "Attack on Titan: Lost Girls",
//   "The Seven Deadly Sins: Signs of Holy War",
//   "Sword Art Online: Alicization - Recollection",
//   "Naruto Shippuden",
//   "Boruto: Naruto Next Generations",
//   "Naruto Shippuden Movie 6: Road to Ninja",
//   "Naruto: Shippuuden Movie 7 - The Last",
//   "Naruto Shippuden Movie 5: Blood Prison",
//   "Naruto Shippuden Movie 3: The Will of Fire",
//   "Naruto Shippuden Movie 4: The Lost Tower",
//   "Naruto Shippuden Movie 1",
//   "Naruto Shippuden Movie 2: Bonds",
//   "Naruto the Movie 2: Legend of the Stone of Gelel",
//   "Naruto the Movie 3: Guardians of the Crescent Moon Kingdom",
//   "Naruto: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo! - Konoha no Sato no Dai Undouaki",
//   "Naruto: Takigakure no Shitou - Ore ga Eiyuu Dattebayo!",
//   "Naruto: Akaki Yotsuba no Clover wo Sagase",
//   "Naruto: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo! Special: Konoha Annual Sports Festival",
//   "Naruto: Honoo no Chuunin Shiken! Naruto vs. Konohamaru!!",
//   "Naruto: The Cross Roads",
//   "Naruto: Shippuuden - Sunny Side Battle",
//   "Naruto: The Lost Story - Mission: Protect the Waterfall Village",
//   "Naruto: Konoha Sports Festival",
//   "Naruto: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo! - Konoha no Sato no Dai Undouaki English Subbed",
//   "Naruto: The Lost Story - Mission: Protect the Waterfall Village English Subbed",
//   "Naruto: The Cross Roads English Subbed",
//   "Naruto: Shippuuden - Sunny Side Battle English Subbed",
//   "Naruto: The Lost Story - Mission: Protect the Waterfall Village English Dubbed",
//   "Naruto: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo! - Konoha no Sato no Dai Undouaki English Dubbed",
//   "Naruto: The Cross Roads English Dubbed",
//   "Naruto: Shippuuden - Sunny Side Battle English Dubbed",
//   "Naruto: Dai Katsugeki!! Yuki Hime Shinobu Houj",
//   "Jujutsu Kaisen",
//   "Attack on Titan: The Final Season",
//   "Demon Slayer: Kimetsu no Yaiba",
//   "My Hero Academia Season 5",
//   "Re:Zero - Starting Life in Another World Season 2",
//   "The Promised Neverland Season 2",
//   "Dr. Stone: Stone Wars",
//   "Horimiya",
//   "Beastars Season 2",
//   "That Time I Got Reincarnated as a Slime Season 2",
//   "The Quintessential Quintuplets Season 2",
//   "Fruits Basket: The Final Season",
//   "Sk8 the Infinity",
//   "So I'm a Spider, So What?",
//   "Cells at Work! Code Black",
//   "Wonder Egg Priority",
//   "Mushoku Tensei: Jobless Reincarnation",
//   "SK∞ (SK8)",
//   "Kemono Jihen",
//   "World Trigger Season 2",
//   "The Seven Deadly Sins: Dragon's Judgement",
//   "The Irregular at Magic High School: Visitor Arc",
//   "Re:Zero - Starting Life in Another World Season 2 Part 2",
//   "Attack on Titan Season 4 Part 2",
//   "The Rising of the Shield Hero Season 2",
//   "Attack on Titan: The Final Season Part 2",
//   "That Time I Got Reincarnated as a Slime Season 2 Part 2",
//   "My Hero Academia Season 6",
//   "The Rising of the Shield Hero Season 3",
//   "Tokyo Revengers Part 2",
//   "SSSS.Gridman",
//   "Fire Force",
//   "Darwin's Game",
//   "The God of High School",
//   "Tower of God",
//   "Gleipnir",
//   "Somali and the Forest Spirit",
//   "Toilet-Bound Hanako-kun",
//   "ID: INVADED",
//   "Keep Your Hands Off Eizouken!",
//   "A Certain Scientific Railgun T",
//   "Magia Record: Puella Magi Madoka Magica Side Story",
//   "Runway de Waratte",
//   "Nekopara",
//   "In/Spectre",
//   "Oda Cinnamon Nobunaga",
//   "BanG Dream! 3rd Season",
//   "Pet",
//   "Infinite Dendrogram",
//   "Smile Down the Runway",
//   "Plunderer",
//   "BOFURI: I Don't Want to Get Hurt, so I'll Max Out My Defense",
//   "Science Fell in Love, So I Tried to Prove It",
//   "My Hero Academia: Heroes Rising",
//   "A Whisker Away",
//   "Hello World",
//   "Ride Your Wave",
//   "Children of the Sea",
//   "Human Lost",
//   "Blackfox",
//   "Weathering with You",
//   "Promare",
//   "Psycho-Pass 3: First Inspector",
//   "The Island of Giant Insects",
//   "Demon Slayer: Kimetsu no Yaiba the Movie: Mugen Train",
//   "Made in Abyss: Dawn of the Deep Soul",
//   "Anohana: The Flower We Saw That Day",
//   "A Silent Voice",
//   "Violet Evergarden: The Movie",
//   "My Hero Academia: Two Heroes",
//   "Demon Slayer: Kimetsu no Yaiba the Movie: Mugen",
//   "Solo Leveling",
// ];

exports.animes = [
  "Cowboy Bebop",
  "Cowboy Bebop: Tengoku no Tobira",
  "Trigun",
  "Witch Hunter Robin",
  "Bouken Ou Beet",
  "Eyeshield 21",
  "Hachimitsu to Clover",
  "Hungry Heart: Wild Striker",
  "Initial D Fourth Stage",
  "Monster",
  "Naruto",
  "One Piece",
  "Tennis no Oujisama",
  "Ring ni Kakero 1",
  "School Rumble",
  "Sunabouzu",
  "Texhnolyze",
  "Trinity Blood",
  "Yakitate!! Japan",
  "Zipang",
  "Shinseiki Evangelion",
  "Shinseiki Evangelion Movie: Shi to Shinsei",
  "Shinseiki Evangelion Movie: Air/Magokoro wo, Kimi ni",
  "Kenpuu Denki Berserk",
  "Koukaku Kidoutai",
  "Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen",
  "Rurouni Kenshin: Meiji Kenkaku Romantan",
  "Rurouni Kenshin: Meiji Kenkaku Romantan - Ishinshishi e no Chinkonka",
  "Akira",
  ".hack//Sign",
  "Aa! Megami-sama!",
  "Aa! Megami-sama! (TV)",
  "Tenshi Kinryouku",
  "Kidou Tenshi Angelic Layer",
  "Ai Yori Aoshi",
  "Appleseed (Movie)",
  "Arc the Lad",
  "Avenger",
  "Beck",
  "Blue Gender",
  "Chobits",
  "Chrno Crusade",
  "D.N.Angel",
  "D.C.: Da Capo",
  "DearS",
  "Rozen Maiden",
  "Rozen Maiden: Träumend",
  "Azumanga Daiou The Animation",
  "Basilisk: Kouga Ninpou Chou",
  "Black Cat (TV)",
  "Cluster Edge",
  "Full Metal Panic!",
  "Full Metal Panic? Fumoffu",
  "Full Metal Panic! The Second Raid",
  "Gakuen Alice",
  "Soukyuu no Fafner: Dead Aggressor",
  "Mahou Shoujo Lyrical Nanoha",
  "Mahou Shoujo Lyrical Nanoha A's",
  "Shuffle!",
  "Kidou Senshi Gundam",
  "Kidou Senshi Gundam: Dai 08 MS Shoutai",
  "Kidou Senshi Gundam 0080: Pocket no Naka no Sensou",
  "Kidou Senshi Gundam: Dai 08 MS Shoutai - Miller's Report",
  "Kidou Senshi Gundam 0083: Stardust Memory",
  "Kidou Senshi Zeta Gundam",
  "Kidou Senshi Gundam ZZ",
  "Kidou Senshi Gundam: Gyakushuu no Char",
  "Kidou Senshi Gundam F91",
  "Kidou Senshi Victory Gundam",
  "Shin Kidou Senki Gundam Wing",
  "Shin Kidou Senki Gundam Wing: Endless Waltz",
  "Kidou Shinseiki Gundam X",
  "Kidou Senshi Gundam SEED",
  "Kidou Senshi Gundam SEED Destiny",
  "Turn A Gundam",
  "Kidou Butouden G Gundam",
  "Last Exile",
  "Mai-HiME",
  "Mai-Otome",
  "Shin Shirayuki-hime Densetsu Prétear",
  "Air",
  "Aishiteruze Baby★★",
  "Akazukin Chacha",
  "Ayashi no Ceres",
  "Boys Be...",
  "Hana yori Dango",
  "Ou Dorobou Jing",
  "Ou Dorobou Jing in Seventh Heaven",
  "Bakuretsu Tenshi",
  "Chuuka Ichiban!",
  "Corrector Yui",
  "Chou Henshin Cosprayers",
  "Uchuu no Stellvia",
  "Sakigake!! Cromartie Koukou",
  "Ijigen no Sekai El-Hazard",
  "Shinpi no Sekai El-Hazard (TV)",
  "Shinpi no Sekai El-Hazard",
  "Shinpi no Sekai El-Hazard Season 2",
  "Final Approach",
  "Fruits Basket",
  "Fullmetal Alchemist",
  "Full Moon wo Sagashite",
  "Fushigi Yuugi",
  "Fushigi Yuugi: Eikouden",
  "Futakoi",
  "Futakoi Alternative",
  "Gate Keepers",
  "Gate Keepers 21",
  "Gensoumaden Saiyuuki",
  "Saiyuuki Reload",
  "Saiyuuki Reload Gunlock",
  "GetBackers",
  "Green Green",
  "Gunslinger Girl",
  "Hikaru no Go",
  "Hunter x Hunter",
  "Hunter x Hunter: Original Video Animation",
  "Hunter x Hunter: Greed Island",
  "Hunter x Hunter: Greed Island Final",
  "Jinki:Extend",
  "Kamikaze Kaitou Jeanne",
  "Kannazuki no Miko",
  "Kanon",
  "Kareshi Kanojo no Jijou",
  "Kono Minikuku mo Utsukushii Sekai",
  "Kimi ga Nozomu Eien",
  "Kita e.: Diamond Dust Drops",
  "Loveless",
  "Blood+",
  "Re: Cutie Honey",
  "Solty Rei",
  "Juuni Kokuki",
  "Shaman King",
  "X/1999",
  "X",
  "Mahou Sensei Negima!",
  "Maria-sama ga Miteru",
  "Boukyaku no Senritsu",
  "Ima, Soko ni Iru Boku",
  "Peace Maker Kurogane",
  "Pita Ten",
  "Power Stone",
  "Mononoke Hime",
  "RahXephon",
  "Samurai 7",
  "Scrapped Princess",
  "s.CRY.ed",
  "Shingetsutan Tsukihime",
  "Slam Dunk",
  "Strange Dawn",
  "Tactics",
  "Tenjou Tenge",
  "Tokyo Underground",
  "Triangle Heart: Sweet Songs Forever",
  "Tsubasa Chronicle",
  "Ultra Maniac",
  "Ultra Maniac OVA",
  "Vandread",
  "Vandread: The Second Stage",
  "Tenkuu no Escaflowne",
  "Whistle!",
  "Xenosaga The Animation",
  "Initial D First Stage",
  "Initial D Second Stage",
  "Initial D Third Stage",
  "Gosenzo San'e",
  "Love Hina",
  "Love Hina Again",
  "Love Hina Christmas Special: Silent Eve",
  "Love Hina Haru Special: Kimi Sakura Chiru Nakare!!",
  "Maburaho",
  "Macross Zero",
  "Onegai☆Teacher",
  "Onegai☆Twins",
  "Rizelmine",
  "Speed Grapher",
  "Sen to Chihiro no Kamikakushi",
  "Tenshi na Konamaiki",
  "Video Girl Ai",
  "Wolf's Rain",
  "Words Worth",
  "Yumeria",
  "Samurai Champloo",
  "Lodoss-tou Senki: Eiyuu Kishi Den",
  "Lodoss-tou Senki",
  "R.O.D: Read or Die",
  "R.O.D: The TV",
  "Ranma ½",
  "Pure Mail",
  "Project A-Ko",
  "Pia Carrot e Youkoso!!",
  "Pia Carrot e Youkoso!! 2",
  "Pia Carrot e Youkoso!! 2 DX",
  "Pia Carrot e Youkoso!!: Sayaka no Koi Monogatari",
  "Shin Angel",
  "Kidou Senkan Nadesico",
  "Kidou Senkan Nadesico: The Prince of Darkness",
  "Kuro no Danshou",
  "Mezzo Forte",
  "Mezzo DSA",
  "Dragon Ball",
  "Dragon Ball GT",
  "Elfen Lied",
  "FLCL",
  "Jigoku Shoujo",
  "Ninin ga Shinobuden",
  "Air Master",
  "Asagiri no Miko",
  "Cardcaptor Sakura",
  "Daa! Daa! Daa!",
  "Dan Doh!!",
  "Meitantei Conan",
  "E's Otherwise",
  "Koukyoushihen Eureka Seven",
  "Rekka no Honoo",
  "Gankutsuou",
  "Genshiken",
  "Girls Bravo: First Season",
  "Gokusen",
  "Gravitation",
  "Agatha Christie no Meitantei Poirot to Marple",
  "Great Teacher Onizuka",
  "Groove Adventure Rave",
  "Harukanaru Toki no Naka de: Hachiyou Shou",
  "Ichigo 100%",
  "InuYasha",
  "Konjiki no Gash Bell!!",
  "Kyou kara Maou!",
  "Madlax",
  "Jungle wa Itsumo Hare nochi Guu",
  "Jungle wa Itsumo Hare nochi Guu Deluxe",
  "Jungle wa Itsumo Hare nochi Guu Final",
  "Hoshi no Koe",
  "Ikkitousen",
  "Hitsuji no Uta",
  "Happy☆Lesson",
  "Happy☆Lesson (TV)",
  "Happy☆Lesson Advance",
  "Happy☆Lesson The Final",
  "Hajime no Ippo",
  "Hajime no Ippo: Champion Road",
  "Hajime no Ippo: Mashiba vs. Kimura",
  "Gunparade March: Arata Naru Kougunka",
  "Gungrave",
  "Golden Boy",
  "Bleach",
  "Hellsing",
  "Gad Guard",
  "Noir",
  "Mahoutsukai ni Taisetsu na Koto",
  "Kiddy Grade",
  "Love♥Love?",
  "Mahoromatic: Automatic Maiden",
  "Mahoromatic: Motto Utsukushii Mono",
  "Viewtiful Joe",
  "Kyougoku Natsuhiko: Kousetsu Hyaku Monogatari",
  "Animal Yokochou",
  "Akane Maniax",
  "Angel Heart",
  "Akage no Anne",
  "Area 88 (TV)",
  "Argento Soma",
  "B'T X",
  "Grappler Baki (TV)",
  "Bakuten Shoot Beyblade",
  "Comic Party",
  "Seikai no Monshou",
  "D.C.S.S: Da Capo Second Season",
  "Dear Boys",
  "Di Gi Charat",
  "Divergence Eve",
  "Divergence Eve 2: Misaki Chronicles",
  "Dragon Drive",
  "Grenadier: Hohoemi no Senshi",
  ".hack//Tasogare no Udewa Densetsu",
];
