exports.animes = [
  "Naruto",
  "One Piece",
  "Bleach",
  "Ninja Kamui",
  "Attack on Titan",
  "My Hero Academia",
  "Death Note",
  "Fullmetal Alchemist: Brotherhood",
  "Dragon Ball Z",
  "Sword Art Online",
  "Demon Slayer",
  "One Punch Man",
  "Hunter x Hunter",
  "Fairy Tail",
  "Tokyo Ghoul",
  "Cowboy Bebop",
  "Neon Genesis Evangelion",
  "Code Geass",
  "Dragon Ball",
  "JoJo's Bizarre Adventure",
  "Steins;Gate",
  "Mob Psycho 100",
  "Black Clover",
  "Kimetsu no Yaiba",
  "Fate/stay night",
  "Psycho-Pass",
  "Fruits Basket",
  "Re:Zero",
  "Gurren Lagann",
  "Yu Yu Hakusho",
  "Noragami",
  "Soul Eater",
  "Durarara!!",
  "Shingeki no Kyojin",
  "Dragon Ball Super",
  "The Seven Deadly Sins",
  "Akame ga Kill!",
  "Mirai Nikki",
  "High School DxD",
  "Gintama",
  "Hellsing",
  "Kuroko's Basketball",
  "Death Parade",
  "Violet Evergarden",
  "No Game No Life",
  "Clannad",
  "Haikyuu!!",
  "Angel Beats!",
  "Tokyo Revengers",
  "Kill la Kill",
  "The Promised Neverland",
  "Overlord",
  "Parasyte",
  "Elfen Lied",
  "Toradora!",
  "Attack on Titan: Junior High",
  "Date A Live",
  "Fairy Tail: Final Series",
  "Goblin Slayer",
  "Devilman: Crybaby",
  "Nanatsu no Taizai",
  "Hajime no Ippo",
  "Baccano!",
  "That Time I Got Reincarnated as a Slime",
  "Akira",
  "Sailor Moon",
  "K-On!",
  "Ao no Exorcist",
  "Sword Art Online II",
  "Shaman King",
  "Boku dake ga Inai Machi",
  "Charlotte",
  "Made in Abyss",
  "Black Butler",
  "Devil May Cry",
  "Love Live! School Idol Project",
  "Kill Me Baby",
  "Inuyasha",
  "Konosuba",
  "School Days",
  "Shokugeki no Souma",
  "Hyouka",
  "Trigun",
  "Rurouni Kenshin",
  "Durarara!!x2 Shou",
  "Yuri!!! on Ice",
  "Mushishi",
  "Danganronpa",
  "The Rising of the Shield Hero",
  "The Ancient Magus' Bride",
  "Claymore",
  "Another",
  "Durarara!!x2 Ten",
  "Tokyo Ghoul:re",
  "Guilty Crown",
  "Plastic Memories",
  "Black Bullet",
  "Devilman Lady",
  "Magi: The Labyrinth of Magic",
  "Mobile Suit Gundam",
  "Trinity Seven",
  "The Future Diary",
  "To Love-Ru",
  "Berserk",
  "Your Lie in April",
  "Initial D",
  "Love, Chunibyo & Other Delusions!",
  "Spice and Wolf",
  "Puella Magi Madoka Magica",
  "Rosario + Vampire",
  "Darker than Black",
  "Attack on Titan Season 3",
  "Fruits Basket: The Final",
  "Attack on Titan Season 2",
  "Attack on Titan Season 4",
  "Attack on Titan Season 1",
  "The Seven Deadly Sins: Wrath of the Gods",
  "Sword Art Online: Alicization",
  "Sword Art Online: Alicization - War of Underworld",
  "Sword Art Online: Alicization - War of Underworld 2nd Season",
  "Attack on Titan: No Regrets",
  "Attack on Titan: Lost Girls",
  "The Seven Deadly Sins: Signs of Holy War",
  "Sword Art Online: Alicization - Recollection",
  "Naruto Shippuden",
  "Boruto: Naruto Next Generations",
  "Naruto Shippuden Movie 6: Road to Ninja",
  "Naruto: Shippuuden Movie 7 - The Last",
  "Naruto Shippuden Movie 5: Blood Prison",
  "Naruto Shippuden Movie 3: The Will of Fire",
  "Naruto Shippuden Movie 4: The Lost Tower",
  "Naruto Shippuden Movie 1",
  "Naruto Shippuden Movie 2: Bonds",
  "Naruto the Movie 2: Legend of the Stone of Gelel",
  "Naruto the Movie 3: Guardians of the Crescent Moon Kingdom",
  "Naruto: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo! - Konoha no Sato no Dai Undouaki",
  "Naruto: Takigakure no Shitou - Ore ga Eiyuu Dattebayo!",
  "Naruto: Akaki Yotsuba no Clover wo Sagase",
  "Naruto: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo! Special: Konoha Annual Sports Festival",
  "Naruto: Honoo no Chuunin Shiken! Naruto vs. Konohamaru!!",
  "Naruto: The Cross Roads",
  "Naruto: Shippuuden - Sunny Side Battle",
  "Naruto: The Lost Story - Mission: Protect the Waterfall Village",
  "Naruto: Konoha Sports Festival",
  "Naruto: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo! - Konoha no Sato no Dai Undouaki English Subbed",
  "Naruto: The Lost Story - Mission: Protect the Waterfall Village English Subbed",
  "Naruto: The Cross Roads English Subbed",
  "Naruto: Shippuuden - Sunny Side Battle English Subbed",
  "Naruto: The Lost Story - Mission: Protect the Waterfall Village English Dubbed",
  "Naruto: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo! - Konoha no Sato no Dai Undouaki English Dubbed",
  "Naruto: The Cross Roads English Dubbed",
  "Naruto: Shippuuden - Sunny Side Battle English Dubbed",
  "Naruto: Dai Katsugeki!! Yuki Hime Shinobu Houj",
  "Jujutsu Kaisen",
  "Attack on Titan: The Final Season",
  "Demon Slayer: Kimetsu no Yaiba",
  "My Hero Academia Season 5",
  "Re:Zero - Starting Life in Another World Season 2",
  "The Promised Neverland Season 2",
  "Dr. Stone: Stone Wars",
  "Horimiya",
  "Beastars Season 2",
  "That Time I Got Reincarnated as a Slime Season 2",
  "The Quintessential Quintuplets Season 2",
  "Fruits Basket: The Final Season",
  "Sk8 the Infinity",
  "So I'm a Spider, So What?",
  "Cells at Work! Code Black",
  "Wonder Egg Priority",
  "Mushoku Tensei: Jobless Reincarnation",
  "SK∞ (SK8)",
  "Kemono Jihen",
  "World Trigger Season 2",
  "The Seven Deadly Sins: Dragon's Judgement",
  "The Irregular at Magic High School: Visitor Arc",
  "Re:Zero - Starting Life in Another World Season 2 Part 2",
  "Attack on Titan Season 4 Part 2",
  "The Rising of the Shield Hero Season 2",
  "Attack on Titan: The Final Season Part 2",
  "That Time I Got Reincarnated as a Slime Season 2 Part 2",
  "My Hero Academia Season 6",
  "The Rising of the Shield Hero Season 3",
  "Tokyo Revengers Part 2",
  "SSSS.Gridman",
  "Fire Force",
  "Darwin's Game",
  "The God of High School",
  "Tower of God",
  "Gleipnir",
  "Somali and the Forest Spirit",
  "Toilet-Bound Hanako-kun",
  "ID: INVADED",
  "Keep Your Hands Off Eizouken!",
  "A Certain Scientific Railgun T",
  "Magia Record: Puella Magi Madoka Magica Side Story",
  "Runway de Waratte",
  "Nekopara",
  "In/Spectre",
  "Oda Cinnamon Nobunaga",
  "BanG Dream! 3rd Season",
  "Pet",
  "Infinite Dendrogram",
  "Smile Down the Runway",
  "Plunderer",
  "BOFURI: I Don't Want to Get Hurt, so I'll Max Out My Defense",
  "Science Fell in Love, So I Tried to Prove It",
  "My Hero Academia: Heroes Rising",
  "A Whisker Away",
  "Hello World",
  "Ride Your Wave",
  "Children of the Sea",
  "Human Lost",
  "Blackfox",
  "Weathering with You",
  "Promare",
  "Psycho-Pass 3: First Inspector",
  "The Island of Giant Insects",
  "Demon Slayer: Kimetsu no Yaiba the Movie: Mugen Train",
  "Made in Abyss: Dawn of the Deep Soul",
  "Anohana: The Flower We Saw That Day",
  "A Silent Voice",
  "Violet Evergarden: The Movie",
  "My Hero Academia: Two Heroes",
  "Demon Slayer: Kimetsu no Yaiba the Movie: Mugen",
  "Solo Leveling",
];
